// Iranian first names in their usual Latin spelling, with the Persian spelling
// people actually use. The rules in `rules.ts` transliterate a SOUND, and no
// Danish sound maps to ع ص ط ح ض — so Ali would come out آلی and Hassan هسن
// without this list. Keys are lowercase; the lookup lowercases and trims.
//
// One name, several Latin spellings: a family writes Hussein or Hossein,
// Mohamed or Muhammad, Sarah or Sara, and every one of them means the same
// Persian word. The alternates map to that one spelling, so the app never
// offers a learner a near-miss of their own name.

export const IRANIAN_NAMES: Record<string, string> = {
  ali: 'علی',
  reza: 'رضا',
  alireza: 'علیرضا',
  maryam: 'مریم',
  mariam: 'مریم',
  babak: 'بابک',
  hassan: 'حسن',
  hasan: 'حسن',
  fatemeh: 'فاطمه',
  fateme: 'فاطمه',
  fatima: 'فاطمه',
  fatemah: 'فاطمه',
  sara: 'سارا',
  sarah: 'سارا',
  hossein: 'حسین',
  hussein: 'حسین',
  hosein: 'حسین',
  mohammad: 'محمد',
  mohamed: 'محمد',
  mohammed: 'محمد',
  muhammad: 'محمد',
  zahra: 'زهرا',
  amir: 'امیر',
  leila: 'لیلا',
  leyla: 'لیلا',
  laila: 'لیلا',
  nima: 'نیما',
  shirin: 'شیرین',
  shireen: 'شیرین',
  dariush: 'داریوش',
  darius: 'داریوش',
  kian: 'کیان',
  yasmin: 'یاسمین',
  yasmine: 'یاسمین',
  jasmin: 'یاسمین',
  jasmine: 'یاسمین',
  omid: 'امید',
  parisa: 'پریسا',
  arash: 'آرش',
  mehdi: 'مهدی',
  mahdi: 'مهدی',
  mehran: 'مهران',
  nasrin: 'نسرین',
  farhad: 'فرهاد',
  farzaneh: 'فرزانه',
  ramin: 'رامین',
  roya: 'رویا',
  sahar: 'سحر',
  saeed: 'سعید',
  said: 'سعید',
  sina: 'سینا',
  soheila: 'سهیلا',
  taraneh: 'ترانه',
  vahid: 'وحید',
  zohreh: 'زهره',
  kaveh: 'کاوه',
  kourosh: 'کوروش',
  kurosh: 'کوروش',
  mina: 'مینا',
  mitra: 'میترا',
  neda: 'ندا',
  negar: 'نگار',
  niloufar: 'نیلوفر',
  pouya: 'پویا',
  pedram: 'پدرام',
  rostam: 'رستم',
  samira: 'سمیرا',
  shahin: 'شاهین',
  shahram: 'شهرام',
  siamak: 'سیامک',
  tara: 'تارا',
  bahram: 'بهرام',
  bijan: 'بیژن',
  ehsan: 'احسان',
  elham: 'الهام',
  golnaz: 'گلناز',
  hamid: 'حمید',
  javad: 'جواد',
  kamran: 'کامران',
  laleh: 'لاله',
  mahsa: 'مهسا',
  nader: 'نادر',
  nazanin: 'نازنین',
  payam: 'پیام',
  rahim: 'رحیم',
  setareh: 'ستاره',
  sepideh: 'سپیده',
  sohrab: 'سهراب',
  behnam: 'بهنام',
  anahita: 'آناهیتا',
  azadeh: 'آزاده',
  fereshteh: 'فرشته',
}
