// The most common Danish first names, spelled the way they SOUND in Persian
// letters — not letter by letter. That is why Mads is ماس (the d is not spoken).
//
// Sound is the rule, but it is not the last word: a spelling that reads as a
// crude Persian word is wrong however right its phonetics are. Signe is سیگنه
// with the silent g written, because سینه is a body part; Kirsten is کرستن,
// because the faithful کیرستن opens on an obscenity; Margrethe is مارگرته, so
// that no reader starts on مرگ. See blocklist.ts.
//
// Lærke is deliberately absent: the rules already spell it لرکه, and the plan
// keeps it as the proof that they can (docs/plans/006-your-name.md, Acceptance).

export const DANISH_NAMES: Record<string, string> = {
  anne: 'آنه',
  anna: 'آنا',
  mette: 'مته',
  søren: 'سورن',
  peter: 'پیتر',
  jens: 'ینس',
  michael: 'میکل',
  mikael: 'میکل',
  mikkel: 'میکل',
  lars: 'لارس',
  thomas: 'توماس',
  henrik: 'هنریک',
  christian: 'کریستیان',
  kristian: 'کریستیان',
  jan: 'یان',
  martin: 'مارتین',
  niels: 'نیلس',
  anders: 'آندرس',
  morten: 'مورتن',
  jesper: 'یسپر',
  mads: 'ماس',
  rasmus: 'راسموس',
  kim: 'کیم',
  ole: 'اوله',
  hans: 'هانس',
  jørgen: 'یورگن',
  claus: 'کلاوس',
  klaus: 'کلاوس',
  bjørn: 'بیورن',
  frederik: 'فردریک',
  jakob: 'یاکوب',
  jacob: 'یاکوب',
  emil: 'امیل',
  oliver: 'اولیور',
  william: 'ویلیام',
  noah: 'نوا',
  magnus: 'مگنوس',
  // The x names live here or nowhere: the sound table does not map x at all,
  // because a name that opens on ک + س opens on a crude word. Inside a word the
  // two letters are simply themselves. Felix and Axel are top-fifty Danish boys'
  // names, so «nowhere» would have meant handing half a classroom the bare
  // alphabet — the list is where they get an answer.
  alexander: 'الکساندر',
  alexandra: 'الکساندرا',
  alex: 'الکس',
  max: 'مکس',
  maxine: 'مکسین',
  felix: 'فلیکس',
  axel: 'اکسل',
  aksel: 'اکسل',
  rex: 'رکس',
  xenia: 'زنیا',
  victor: 'ویکتور',
  anton: 'آنتون',
  carl: 'کارل',
  elias: 'الیاس',
  lucas: 'لوکاس',
  oscar: 'اسکار',
  august: 'آگوست',
  johan: 'یوهان',
  erik: 'اریک',
  simon: 'سیمون',
  daniel: 'دانیل',
  andreas: 'آندریاس',
  benjamin: 'بنیامین',
  tobias: 'توبیاس',
  nikolaj: 'نیکولای',
  nikolai: 'نیکولای',
  nicolai: 'نیکولای',
  kirsten: 'کرستن',
  hanne: 'هانه',
  helle: 'هله',
  susanne: 'سوسانه',
  lene: 'لنه',
  maria: 'ماریا',
  marianne: 'ماریانه',
  camilla: 'کامیلا',
  kamilla: 'کامیلا',
  louise: 'لوئیزه',
  charlotte: 'شارلوته',
  inge: 'اینگه',
  karen: 'کارن',
  julie: 'یولیه',
  ida: 'ایدا',
  sofie: 'سوفیه',
  sophie: 'سوفیه',
  emma: 'اما',
  freja: 'فرایا',
  clara: 'کلارا',
  laura: 'لاورا',
  astrid: 'آسترید',
  signe: 'سیگنه',
  // The whole Margrethe family, spelled with the ا Danish really says. Sound
  // alone would open every one of them on مرگ — «død» — so the list carries the
  // family rather than one member of it. See blocklist.ts.
  margrethe: 'مارگرته',
  margrete: 'مارگرته',
  margit: 'مارگیت',
  marga: 'مارگا',
  marge: 'مارگه',
  margrit: 'مارگریت',
  margaretha: 'مارگارتا',
  margarethe: 'مارگارته',
  katrine: 'کاترینه',
  kathrine: 'کاترینه',
  cecilie: 'سیسیلیه',
  amalie: 'آمالیه',
  caroline: 'کارولینه',
  line: 'لینه',
  trine: 'ترینه',
  rikke: 'ریکه',
  pia: 'پیا',
  lone: 'لونه',
  bente: 'بنته',
}
